first_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('url_shortener/', include('urlShortener.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

urlShortener/urls.py
from django.urls import path

from . import views

app_name = 'urlShortener'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:url_link_id>/', views.detail, name='detail'),
    path('shorten/', views.shorten, name='shorten'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

urlShortener/models.py
from django.db import models

# Create your models here.
class UrlLink(models.Model):
    original_url = models.URLField(max_length=200)

    def __str__(self):
        return self.original_url

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

urlShortener/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404, render

from .models import UrlLink

# Create your views here.
class IndexView(generic.ListView):
    model = UrlLink
    template_name = 'urlShortener/index.html'
    context_object_name = 'short_url_list'

    def get_queryset(self):
        return UrlLink.objects.all()

def detail(request, url_link_id):
    url_link = get_object_or_404(UrlLink, pk=url_link_id)
    return render(request, 'urlShortener/detail.html', {'url_link': url_link})

def shorten(request):
    new_url = UrlLink(original_url = request.POST['original_url'])
    new_url.save()
    return HttpResponseRedirect(reverse('urlShortener:detail', args=(str(new_url.id),)))

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %} {% for choice in question.choice_set.all %}
    <input
      type="radio"
      name="choice"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
    ><br />
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

urlShortener/templates/urlShortener/detail.html
<a href="{% url 'urlShortener:index' %}">Back</a>
<h1>UrlLink Details</h1>
<span><b>Original URL:</b></span>
<a href={{ url_link.original_url }} target='_blank'>{{ url_link.original_url }}</a>

urlShortener/templates/urlShortener/index.html
<div
  style="
    align-items: center;
    display: flex-column;
    flex-direction: column;
    height: 100%;
    justify-content: center;
  "
>
  <form action="{% url 'urlShortener:shorten' %}" method="post">
    {% csrf_token %}
    <fieldset>
      {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
      {% endif %}

      <label for="original_url">Enter a URL:</label>
      <input type="url" name="original_url" id="original_url" placeholder="https://example.com" required />
    </fieldset>
    <input type="submit" value="Shorten URL" />
  </form>

  {% if short_url_list %}
  <h1>List of Shortened URLs</h1>
  <ul>
    {% for url in short_url_list %}
    <li>
        <span><b>Link {{ forloop.counter }}: {{url.original_url}}</b></span>
      <a href="{% url 'urlShortener:detail' url.id %}" style='color: brown;'>View Details</a>
      <a href="{{url.original_url}}" target='_blank' style='color: cadetblue;'>Go to URL</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No Shortened URLs to see.</p>
  {% endif %}
</div>